version: "2"

services:
  j2e-app:
    image: alchimiste3/j2e-app-use
    ports:
      - "8080:8080"
    networks:
      - reseau

  dotnet-app:
    image: cyrus8/dotnet-app
    ports:
      - "9090:9090"
    networks:
      - reseau


networks:
  reseau:
  
