version: "2"

services:
  j2e-app:
    image: alchimiste3/j2e-app-use
    ports:
      - "8080:8080"
    network_mode: "host"
    volumes:
     - ./dataJ2eCompo:/app

  dotnet-app:
    image: alchimiste3/dotnet-app
    ports:
      - "9090:9090"
    network_mode: "host"

  
